<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Table `masa_aktif` (docs/06 §6.6). `terbuka_kunci` is generated by MySQL.
 */
class MasaAktifModel extends Model
{
    protected $table         = 'masa_aktif';
    protected $returnType    = 'array';
    protected $useTimestamps = true;
    protected $dateFormat    = 'datetime';
    protected $allowedFields = ['siswa_id', 'tanggal_mulai', 'tanggal_selesai', 'alasan_nonaktif', 'keterangan_nonaktif', 'dibatalkan', 'dibuat_oleh', 'dinonaktifkan_oleh'];
}
