<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Table `tahun_ajaran` (docs/06 §6.2). `aktif_kunci` is generated by MySQL.
 */
class TahunAjaranModel extends Model
{
    protected $table         = 'tahun_ajaran';
    protected $returnType    = 'array';
    protected $useTimestamps = true;
    protected $dateFormat    = 'datetime';
    protected $allowedFields = ['nama', 'tanggal_mulai', 'tanggal_selesai', 'aktif'];
}
